name: Sync GitHub Comments to Jira

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  sync-comment:
    runs-on: ubuntu-latest
    steps:
      # Debug Variables
      - name: Use variables
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}"
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}

      # Extract Issue Details
      - name: Extract GitHub Issue Details
        id: extract_details
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV

      # Find Associated Jira Issue by Title
      - name: Find Associated Jira Issue by Title
        id: find_jira
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          ISSUE_TITLE: ${{ env.ISSUE_TITLE }}
          JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}
        run: |
          # Escape special characters in title
          ESCAPED_TITLE=$(echo "$ISSUE_TITLE" | sed 's/"/\\"/g')

          # Search Jira issue by title
          RESPONSE=$(curl -s -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            "$JIRA_URL/rest/api/3/search?jql=project=$JIRA_PROJECT_KEY+AND+summary~\"$ESCAPED_TITLE\"")

          echo "Jira Search Response: $RESPONSE"

          # Extract Jira Issue Key
          JIRA_ISSUE_KEY=$(echo "$RESPONSE" | jq -r '.issues[0].key')

          if [ -z "$JIRA_ISSUE_KEY" ] || [ "$JIRA_ISSUE_KEY" == "null" ]; then
            echo "Jira issue not found for GitHub issue title: $ISSUE_TITLE"
            exit 0
          fi

          echo "JIRA_ISSUE_KEY=$JIRA_ISSUE_KEY" >> $GITHUB_ENV

      # Add Comment to Jira
      - name: Add Comment to Jira
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_KEY: ${{ env.JIRA_ISSUE_KEY }}
          COMMENT_BODY: ${{ env.COMMENT_BODY }}
        run: |
          RESPONSE=$(curl -X POST \
            -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "'"$COMMENT_BODY"'"
                      }
                    ]
                  }
                ]
              }
            }' \
            "$JIRA_URL/rest/api/3/issue/$JIRA_ISSUE_KEY/comment")

          echo "Comment Response: $RESPONSE"

