on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  sync-comment:
    runs-on: ubuntu-latest
    env:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}

    steps:
      # Debug Variables
      - name: Debug Variables
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}"
          echo "JIRA_URL: $JIRA_URL"
          echo "JIRA_USERNAME: $JIRA_USERNAME"

      # Extract Issue Details
      - name: Extract GitHub Issue Details
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV

      # Find Associated Jira Issue by Title
      - name: Find Associated Jira Issue by Title
        env:
          ISSUE_TITLE: ${{ env.ISSUE_TITLE }}
        run: |
          echo "Issue TITLE: $ISSUE_TITLE"
          ESCAPED_TITLE=$(echo "$ISSUE_TITLE" | sed 's/"/\\"/g')
          echo "ESCAPED_TITLE is: $ESCAPED_TITLE"
          
          RESPONSE=$(curl -s -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            "$JIRA_URL/rest/api/3/search?jql=project=$JIRA_PROJECT_KEY+AND+summary~\"$ESCAPED_TITLE\"")
          
          echo "Jira Search Response: $RESPONSE"
          JIRA_ISSUE_KEY=$(echo "$RESPONSE" | jq -r '.issues[0].key')
          echo "JIRA_ISSUE_KEY=$JIRA_ISSUE_KEY" >> $GITHUB_ENV

      # Add Comment to Jira
      - name: Add Comment to Jira
        env:
          JIRA_ISSUE_KEY: ${{ env.JIRA_ISSUE_KEY }}
          COMMENT_BODY: ${{ env.COMMENT_BODY }}
        run: |
          curl -X POST \
            -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "'"$COMMENT_BODY"'"
                      }
                    ]
                  }
                ]
              }
            }' \
            "$JIRA_URL/rest/api/3/issue/$JIRA_ISSUE_KEY/comment"


