name: Jira-GitHub Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      issueKey:
        description: 'The Jira issue key associated with the event'
        required: true
      state:
        description: 'The status of the Jira issue'
        required: true
        default: 'Open'
      comment:
        description: 'The most recent comment on the Jira issue'
        required: false
      body:
        description: 'Additional details from Jira'
        required: true

jobs:
  process-jira-update:
    name: Process Jira Update
    runs-on: ubuntu-latest

    steps:
      - name: Log Inputs
        run: |
          echo "Jira Issue Key: ${{ github.event.inputs.issueKey }}"
          echo "Jira Status: ${{ github.event.inputs.state }}"
          echo "Jira Comment: ${{ github.event.inputs.comment }}"
          echo "Details: ${{ github.event.inputs.body }}"

      - name: Update GitHub Issue/PR
        env:
          API_GH_TOKEN: ${{ secrets.API_GH_TOKEN }}
        run: |
          # Extract issue/PR number dynamically using Jira issue key
          issue_number=$(echo "${{ github.event.inputs.body }}" | grep -oE '[0-9]+$')
          echo "Updating GitHub Issue/PR #$issue_number"
          
          if [ "${{ github.event.inputs.state }}" = "Done" ]; then
            curl -X PATCH \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $API_GH_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/issues/$issue_number \
              -d '{"state": "closed"}'
          else
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $API_GH_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/comments \
              -d '{"body": "Jira Status Updated: '"${{ github.event.inputs.state }}"'\\nJira Comment: '"${{ github.event.inputs.comment }}"'"}'

